apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: dapr-secrets
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: $KEYVAULT_NAME