kind: Service
apiVersion: v1
metadata:
  name: dapr-secrets
  labels:
    app: dapr-secrets
spec:
  selector:
    app: dapr-secrets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer