apiVersion: dapr.io/v1alpha1
kind: Component
namespace: dapr-secrets
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: $KEYVAULT_NAME